-- MySQL Script generated by MySQL Workbench
-- Fri Mar 27 22:44:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `bio` TEXT(300) NULL,
  `avatar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Channel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Channel_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Channel_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Channel_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `message` VARCHAR(300) NULL,
  `filepath` VARCHAR(45) NULL,
  `updateat` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Channel_has_User1_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Channel_has_User1_Channel1_idx` (`Channel_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Channel_has_User1_Channel1`
    FOREIGN KEY (`Channel_id`)
    REFERENCES `mydb`.`Channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Channel_has_User1_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `Channel_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`Channel_id`, `User_id`),
  INDEX `fk_Channel_has_User1_User2_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Channel_has_User1_Channel2_idx` (`Channel_id` ASC) VISIBLE,
  CONSTRAINT `fk_Channel_has_User1_Channel2`
    FOREIGN KEY (`Channel_id`)
    REFERENCES `mydb`.`Channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Channel_has_User1_User2`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Message_Channel_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `commentaire` VARCHAR(300) NULL,
  INDEX `fk_Commentaire_Message1_idx` (`Message_Channel_id` ASC) VISIBLE,
  INDEX `fk_Commentaire_User1_idx` (`User_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Commentaire_Message1`
    FOREIGN KEY (`Message_Channel_id`)
    REFERENCES `mydb`.`Message` (`Channel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
